template_path: "sc-tag-options.j2"
stack_name: "sc-tag-options"
dependencies:
  - "prod/sc-portfolio-ec2.yaml"
  - "prod/sc-portfolio-s3-basic.yaml"
sceptre_user_data:
  Departments:
    - "Platform"
    - "CompOnc"
    - "SysBio"
  Projects:
    - "Infrastructure"
    - "dream"
    - "htan"
    - "iAtlas"
    - "amp-ad"
    - "genie"
    - "neurofibromatosis"
    - "challenge" # Sometimes challenges aren't always DREAM
    - "pson"
    - "csbs"
    - "dream/metadata"
  OwnerEmails:
    - "khai.do@sagbase.org"
    - "tess.thyer@sagebase.org"
    - "joe.smith@sagebase.org"
    - "xengie.doan@sagebase.org"
  ProductIDs:
    - "port-z2m47jv6sckgi"   # EC2 RA portfolio
    - "port-4suvomoj5jto6"   # S3 basic portfolio
