language: python
python: 3.6
cache: pip
install:
  - wget https://github.com/Sage-Bionetworks/infra-utils/archive/master.zip -O /tmp/infra-utils.zip
  - unzip -j -n /tmp/infra-utils.zip -x "infra-utils-master/.gitignore" "infra-utils-master/LICENSE" "infra-utils-master/*.md" "infra-utils-master/aws/*"
  - ./setup_aws_cli.sh || travis_terminate 1
  - pip install pre-commit sceptre sceptre-ssm-resolver sceptre-date-resolver
stages:
  - name: validate
  - name: deploy
    if: branch = master AND type = push
jobs:
  fast_finish: true
  include:
    - stage: validate
      script:
        - pre-commit autoupdate
        - pre-commit run --all-files
    - stage: deploy
      script: sceptre --debug launch prod --yes
